LLAVA_CLIP_PATH = './checkpoints/CLIP_VIT/'
LLAVA_MODEL_PATH = './checkpoints/llava_v1.5-13b/llava'
SDXL_PATH = './checkpoints/Real_4_SDXL/'
foundirv2_PATH =  './checkpoints/foundirv2.bin'
VAE_FP16_PATH = './checkpoints/VAE_FP16/'
BSRNet_PATH = './checkpoints/BSRNet.pth'